### ISSUE TITLE
11-15-17 Version 1.1.1 Welcome [name] won't keep name value

### ISSUE THREAD

**Issue by mkalluri21** [manrajsingh960/GetTogether#10]
After logging in, the user will see the message "Welcome, <username>" If the user navigates to another pages then navigates to the home page, the message will instead display "Welcome, null." The message on the home page should keep displaying "Welcome, <username>" no matter what page the user navigates to and from.

**Comment by manrajsingh960** [comment]
I think this is fixed if im not mistakne
