### ISSUE TITLE
11-15-17 Version 1.1.1 Logout and back button brings you back to home screen

### ISSUE THREAD

**Issue by mkalluri21** [manrajsingh960/GetTogether#11]
If the user logs out of their account and then presses the back button on their android device, they will end up back at the home page for the app. Once the user logs out, nothing they do except for logging in should allow them to see the other pages of the app.

**Comment by manrajsingh960** [comment]
I just noticed this. Thanks.

**Comment by manrajsingh960** [comment]
Solved.
