### ISSUE TITLE
Events list is empty

### ISSUE THREAD

**Issue by manrajsingh960** [manrajsingh960/GetTogether#28]
Events list shows up as empty when it should not 
Created events list also shows up as empty when it should not

**Comment by trulylee** [comment]
FYI: Events are limited to having ended after current hour. Updated test data for end date of 3 days from now.

**Comment by trulylee** [comment]
TO UPDATE event end date to 3 days in future run this in DB:
UPDATE event SET event_enddatetime = DATE_ADD(event_enddatetime, INTERVAL 3 DAY);

NOTE: This only works for the event table. Other tables must be updated separately
