### ISSUE TITLE
Join Events empty/bad until refresh

### ISSUE THREAD

**Issue by trulylee** [manrajsingh960/GetTogether#29]
Join Events tab is empty on initial click (or bad with old data) until "refresh" is clicked.
![image](https://user-images.githubusercontent.com/32374933/33521011-d261c3b8-d77a-11e7-83a4-808824bc5ae6.png)
After Refresh:
![image](https://user-images.githubusercontent.com/32374933/33521013-e44742ce-d77a-11e7-8258-ca69673b5c2d.png)

**Comment by manrajsingh960** [comment]
You don't have the updated code. This issue is fixed on the most recent commit to github.

**Comment by manrajsingh960** [comment]
To update the code go to VCS in the menu and then click on update project icon
