### ISSUE TITLE
Nothing shows when I go to join event

### ISSUE THREAD

**Issue by trulylee** [manrajsingh960/GetTogether#42]
So it doesn't happen every time but happens way too much. I am using the WiFi at school aND the current APK. I go to join an event and nothing shows. I hit refresh. Same thing. It happens more often when I run the emulator in android btw.
Then I go back and try the same button and stuff shows. Weird?  Annoying.

**Comment by manrajsingh960** [comment]
To fix this I added a progress dialog that will wait until there is a response or the user has option to retry. If the internet is really slow, then you may need to retry a couple times before you eventually see the list.

**Comment by trulylee** [comment]
To fix this I changed the SQL code so it gives back the rows again.
