### ISSUE TITLE
11-7-17 Version 1.0.1 Map not functioning correctly

### ISSUE THREAD

**Issue by mkalluri21** [manrajsingh960/GetTogether#8]
Instead of displaying the google map, the screen shows a blank white space.

**Comment by dcortez2** [comment]
When you click on the map feature, It crashes the app but then asks for the app to access the phones location. When opening the app again and trying the map feature again, It doesn't crash, but the map then takes you to a blank white map screen.

**Comment by mkalluri21** [comment]
Removing map feature from app.
